version: '3'
services:
  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./src:/var/www/html/
      - /usr/local/etc/php/7.4/cli/php.ini
    networks:
      - internal
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
